export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_MORE_OPTIONS = 'TOGGLE_MORE_OPTIONS'
export const UPDATE_HEADER = 'UPDATE_HEADER'

export const YT_PLAYER_STATUS_CHANGED = 'YT_PLAYER_STATUS_CHANGED'

export const YT_PLAYER_PLAYING = 'YT_PLAYER_PLAYING'
export const YT_PLAYER_BUFFERING = 'YT_PLAYER_BUFFERING'
export const YT_PLAYER_PAUSED = 'YT_PLAYER_PAUSED'
export const YT_PLAYER_ENDED = 'YT_PLAYER_ENDED'
export const YT_PLAYER_CUED = 'YT_PLAYER_CUED'